### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by kevvurs** [couchbaselabs/try-cb-java#14]
tests?

**Comment by osfameron** [comment]
Thanks @kevvurs, we've recently updated all the sample apps to support new features in Couchbase Server 7.0.
Adding tests is on our roadmap for improving the quality of this as a valid example.
If you have any recommendations for Java testing library/framework to go for in 2021, we'll take them into consideration!

**Comment by osfameron** [comment]
REST functional tests added, see README for usage.
