### ISSUE TITLE
java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by scienartist** [couchbaselabs/try-cb-java#3]
I started a Couchbase server locally using Docker.
`docker run -d -p 8091:8091 couchbase`
http://localhost:8091 is available, and the travel-sample is loaded.

I failed to run the sample application following the guide, running `mvn spring-boot:run` in the directory, but I got this:
`java.net.ConnectException: Connection refused: localhost/127.0.0.1:11210`
then I tried with custom options but still got the same error.

Noticed that the port 11210 the app tried to connect was wrong, I started another server, and tried to connect again:
`docker run -d -p 11210:11210 couchbase`
then the exception changed: `java.net.ConnectException: Connection refused: localhost/127.0.0.1:8092`

I wonder which file should I edit and how to connect with Couchbase.

**Comment by meghalidhoble** [comment]
Hi @jinpng , 
I am also facing similar issue and seeing "connection refused error for 11210 port". 
Could you please provide any pointers, how could you fix this one? 

Thanks,
Meghali
